version: "3.9"

services:
  server:
    build:
      context: ./apps/server
      dockerfile: Dockerfile
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: file:./db/local.db
    volumes:
      - ./apps/server/db:/app/db
    restart: unless-stopped

  web:
    build:
      context: ./apps/web
      dockerfile: Dockerfile
      args: # <-- Pass build args here
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
        NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
    environment: # <-- Runtime env vars here
      NODE_ENV: production
      PORT: 3001
      NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
      NEXT_PUBLIC_SERVER_URL: ${NEXT_PUBLIC_SERVER_URL}
    depends_on:
      - server
    restart: unless-stopped
